language: java
jdk:
- oraclejdk8
#- oraclejdk7

env:
  global:
  - BINTRAY_USER=danielpeintner
  - secure: iRucNDmK9KeXtFL8B0rdGQMqBB22roAw4h2aCL98CJCHz5QqS9/3Y/+Ayc6Q2cFfdo6QcLPLiwDn6Nu0zGGwMJmqokZqUvhE6CfAOqwG/XHqwTOJqVdaQGXWfqpQZ5K1RX6oXBp0vUTef+IpDiqd2BDVAGX3IWFEW0FB2R9k5yCqYkiw84hCC+EIcZxySuXRhfSkotpAmIsjHsTi/kgxLps1mNrQvP96AH8YiIgi/LIAnfoJj9RI44LsSYF/3yro9OWTuSkVlPRBvH+ohirZWbiSF6lJ0KSguzo6iWTSylcfNjsfjKL9hOmYpKzNzEvWzZxNRd1GC6U3P0cpO7utQxmou0nWCrzKTH2gXW98eH3RP8cooTvcKo/6Mdy0LlDQwldw0jf0sYKgWA8uznIVU1RW4+chBHg6/zwZNbNWaxn3sAyBkQlvsD/Bot9H7EVGciGL8kI10i4JtKFrlkq2Ap1WLwO+R52kygR2wzV90hKbMDz3iSHd4LbYHoNCAZfKwt/uqIcnCImizTKApiStWkzEJCMuziZieSLN/mReTd3Cg3pfjwEH96IE0rzcmVZOJ3i8waYnZd8dIY/KBjGNdcFMNTHPjzcNy/50Sc9FhGbXfPyM+BEPyiUfX0ghKFHP1C7HH3GM4Q/e4oXGGzRvZkZGdi80G49G+7RXUaFR8U4=
after_success:
- gradle test
- gradle bintrayUpload
